name: Build and Test Mod

on:
  push:
    branches:
      - main  # Run on push to main
  pull_request:
    branches:
      - main  # Run on PR to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest  # Change to windows-latest if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Required for Forge and Fabric

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build the mod
        run: ./gradlew build --stacktrace

      - name: Upload built mod as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-mod
          path: build/libs/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Test mod loading
        run: ./gradlew runClient --stacktrace  # Runs the Minecraft client with the mod (headless mode)

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download built mod
        uses: actions/download-artifact@v4
        with:
          name: built-mod
          path: mod-build

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: mod-build/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Проверка загрузки мода
        run: ./gradlew runClient --stacktrace
